=== HubertCitko/Web-Application-Development-Study-Project/web/FilmySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Filmy" type="FilmListType"/>
    <xs:complexType name="FilmType">
        <xs:sequence>
            <xs:element name="Tytul" type="TitleType"/>
            <xs:element name="Rezyser" type="PersonType"/>
            <xs:element name="RokProdukcji" type="YearType"/>
            <xs:element name="Gatunek" type="GenreType"/>
            <xs:element name="Ocena">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="10"/>
                        <xs:fractionDigits value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Aktorzy" type="ActorsType"/>
            <xs:element name="CzasTrwaniaWMinutach" type="DurationType"/>
            <xs:element name="Formaty" type="FormatListType"/> 
        </xs:sequence>
        <xs:attribute name="ID" type="CustomIDType" use="required"/>
    </xs:complexType>
    <xs:group name="PersonDetailsGroup">
        <xs:sequence>
            <xs:element name="Imie" type="xs:string"/>
            <xs:element name="Nazwisko" type="xs:string"/>
        </xs:sequence>
    </xs:group>
    <xs:complexType name="PersonType">
        <xs:sequence>
            <xs:group ref="PersonDetailsGroup"/>
        </xs:sequence>
        <xs:attribute name="Narodowosc" type="xs:string"/>
        <xs:attribute ref="Wiek"/>
    </xs:complexType>


    <xs:complexType name="ActorsType">
        <xs:choice>
            <xs:element name="Aktor" type="ActorType" maxOccurs="unbounded"/>
            <xs:element name="BrakAktorow" type="xs:string" fixed="Nieznani aktorzy"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="ActorType">
        <xs:sequence>
            <xs:element name="DaneAktora">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Imie" type="xs:string"/>
                        <xs:element name="Nazwisko" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="NazwaRoli" type="xs:string"/>
            <xs:element name="Zdjecie" type="xs:anyURI"/>
            <xs:element name="Link" type="xs:anyURI"/> 
            
        </xs:sequence>
        <xs:attribute name="Nagrodzony" type="xs:boolean"/>
        <xs:attribute ref="Wiek"/>
        
    </xs:complexType>
    
    <xs:complexType name="ExtendedFilmType">
        <xs:complexContent>
            <xs:extension base="FilmType">
                <xs:sequence>
                    <xs:element name="StudioProdukcji" type="StudioType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name = "StudioType">
        <xs:sequence>
            <xs:element name="Nazwa" type="xs:string"/>
            <xs:element name="Miasto" type="xs:string"/>
            <xs:element name="Kraj" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>


     <xs:simpleType name="YearType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1888"/>
            <xs:maxInclusive value="2100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="DurationType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="500"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GenreType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Drama"/>
            <xs:enumeration value="Comedy"/>
            <xs:enumeration value="Action"/>
            <xs:enumeration value="Horror"/>
            <xs:enumeration value="Sci-Fi"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="TitleType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="200"/>
        </xs:restriction>
    </xs:simpleType>
    

    <xs:simpleType name="FormatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Blu-ray"/>
            <xs:enumeration value="DVD"/>
            <xs:enumeration value="VHS"/>
            <xs:enumeration value="Streaming"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="FormatListType">
        <xs:list itemType="FormatType"/>
    </xs:simpleType>
    <xs:simpleType name="CustomIDType">
        <xs:union memberTypes="xs:string xs:integer"/>
    </xs:simpleType>
    <xs:attribute name="Wiek" type="xs:integer"/>

    <xs:complexType name = "FilmListType">
        <xs:sequence>
            <xs:element name="Film" type="ExtendedFilmType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== HubertCitko/Web-Application-Development-Study-Project/web/Filmy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Filmy SYSTEM "Filmy.dtd">
<Filmy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FilmySchema.xsd">
    <Film ID="12345">
        <Tytul>Incepcja</Tytul>
        <Rezyser Narodowosc="Brytyjska" Wiek="50">
            <Imie>Christopher</Imie>
            <Nazwisko>Nolan</Nazwisko>
        </Rezyser>
        <RokProdukcji>2010</RokProdukcji>
        <Gatunek>Sci-Fi</Gatunek>
        <Ocena>9.0</Ocena>
        <Aktorzy>
            <Aktor Nagrodzony="true" Wiek="45">
                <DaneAktora>
                    <Imie>Leonardo</Imie>
                    <Nazwisko>DiCaprio</Nazwisko>
                </DaneAktora>
                <NazwaRoli>Dom Cobb</NazwaRoli>
                <Zdjecie>https://example.com/leonardo.jpg</Zdjecie>
                <Link>https://www.imdb.com/name/nm0000138/</Link>
            </Aktor>
            <Aktor Nagrodzony="false" Wiek="40">
                <DaneAktora>
                    <Imie>Joseph</Imie>
                    <Nazwisko>Gordon-Levitt</Nazwisko>
                </DaneAktora>
                <NazwaRoli>Arthur</NazwaRoli>
                <Zdjecie>https://example.com/joseph.jpg</Zdjecie>
                <Link>https://www.imdb.com/name/nm0330687/</Link>
            </Aktor>
            <Aktor Nagrodzony="true" Wiek="36">
                <DaneAktora>
                    <Imie>Elliot</Imie>
                    <Nazwisko>Page</Nazwisko>
                </DaneAktora>
                <NazwaRoli>Ariadne</NazwaRoli>
                <Zdjecie>https://example.com/elliot.jpg</Zdjecie>
                <Link>https://www.imdb.com/name/nm0680983/</Link>
            </Aktor>
        </Aktorzy>
        <CzasTrwaniaWMinutach>148</CzasTrwaniaWMinutach>
        <Formaty>Blu-ray DVD Streaming</Formaty>
        <StudioProdukcji>
            <Nazwa>Warner Bros.</Nazwa>
            <Miasto>Burbank</Miasto>
            <Kraj>USA</Kraj>
        </StudioProdukcji>
    </Film>
    <Film ID="67890">
        <Tytul>Avatar</Tytul>
        <Rezyser Narodowosc="Kanadyjska" Wiek="69">
            <Imie>James</Imie>
            <Nazwisko>Cameron</Nazwisko>
        </Rezyser>
        <RokProdukcji>2009</RokProdukcji>
        <Gatunek>Sci-Fi</Gatunek>
        <Ocena>8.5</Ocena>
        <Aktorzy>
            <Aktor Nagrodzony="false" Wiek="48">
                <DaneAktora>
                    <Imie>Sam</Imie>
                    <Nazwisko>Worthington</Nazwisko>
                </DaneAktora>
                <NazwaRoli>Jake Sully</NazwaRoli>
                <Zdjecie>https://example.com/sam.jpg</Zdjecie>
                <Link>https://www.imdb.com/name/nm0941777/</Link>
            </Aktor>
        </Aktorzy>
        <CzasTrwaniaWMinutach>162</CzasTrwaniaWMinutach>
        <Formaty>Blu-ray Streaming</Formaty>
        <StudioProdukcji>
            <Nazwa>20th Century Fox</Nazwa>
            <Miasto>Los Angeles</Miasto>
            <Kraj>USA</Kraj>
        </StudioProdukcji>
    </Film>
    <Film ID="54321">
        <Tytul>Shrek</Tytul>
        <Rezyser Narodowosc="Amerykańska" Wiek="60">
            <Imie>Andrew</Imie>
            <Nazwisko>Adamson</Nazwisko>
        </Rezyser>
        <RokProdukcji>2001</RokProdukcji>
        <Gatunek>Comedy</Gatunek>
        <Ocena>8.0</Ocena>
        <Aktorzy>
            <Aktor Nagrodzony="false" Wiek="65">
                <DaneAktora>
                    <Imie>Mike</Imie>
                    <Nazwisko>Myers</Nazwisko>
                </DaneAktora>
                <NazwaRoli>Shrek</NazwaRoli>
                <Zdjecie>https://example.com/mike.jpg</Zdjecie>
                <Link>https://www.imdb.com/name/nm0000196/</Link>
            </Aktor>
        </Aktorzy>
        <CzasTrwaniaWMinutach>90</CzasTrwaniaWMinutach>
        <Formaty>DVD VHS</Formaty>
        <StudioProdukcji>
            <Nazwa>DreamWorks</Nazwa>
            <Miasto>Glendale</Miasto>
            <Kraj>USA</Kraj>
        </StudioProdukcji>
    </Film>
</Filmy>
